version: '3.8'

services:
  web:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sgssi_db
      MYSQL_USER: sgssi_user
      MYSQL_PASSWORD: sgssi_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: